### PR TITLE
136 editorial branch

### PR DESCRIPTION
**Pull request by amilan17**
editorial updates of branch for issue #136

### CODE REVIEW

**Comment by amilan17** [comment]
@antoinemerle @marijanacrepulja -- I created a separate branch to introduce a lot of editorial changes for issue #136. Can you please review to ensure that I didn't change the meaning of any content?

**Comment by antoinemerle** [comment]
Dear @amilan17 ,

You did not change anything related to the creation of the additonnal lines for my products , but I am not sure about the following :
Some lines were modified but are not part of my initial PR : 
ex :

from: 
```
21,Radar data,021121,SEAWINDS NOF rain index,Numeric,0,0,8,Numeric,0,3,*,106,Operational
to
21,Radar data,021121,SEAWINDS NOF rain index,Numeric,0,0,8,Numeric,0,3,,,Operational
```

or that one :

```
21,Radar data,021189,Corrected OCOG backscatter coefficient (negative reference),dB,2,-32768,16,dB,2,6,*,"112,11",Operational
21,Radar data,021189,Corrected OCOG backscatter coefficient (negative reference),dB,2,-32768,16,dB,2,6,(see Note),11,Operational
```


can you confirm my thoughts ? and confirm it is not a problem for you .

thanks

**Comment by amilan17** [comment]
@antoinemerle -- I haven't checked your new lines yet. This PR was created before that addition. The other changes are just cleanup for alignment with the published PDF and are unrelated to this issue.

**Review by antoinemerle — APPROVED** [review]
Everything seems fine to me : thanks a lot for spending time to correct those one, for FT-2 I will improve my script to respect that nomenclature.

I approve the following

**Pull request merged**
